### ISSUE TITLE
Date formatting using moment.js

### ISSUE THREAD

**Issue by mshd** [maxlath/wikibase-sdk#75]
Could I make a PR using moment.js to format dates, since many projects using this library have to do the same thing.
This is what we have so far: https://github.com/ogroppo/entitree/blob/master/src/lib/formatDateClaim.js

**Comment by maxlath** [comment]
I would prefer to maximize compatibility in a standard way, rather than forcing moment.js on all lib users, especially as most people [don't need moment.js](https://github.com/you-dont-need/You-Dont-Need-Momentjs) anymore, and momentjs.com itself recommends to not start using it now:

> Considering using Moment in your project?
> There may be better modern alternatives.
> For more details and recommendations,
> please see [Project Status](https://momentjs.com/docs/#/-project-status/) in the docs.

The more pressing issue in my opinion would rather be to address the issue #54 which could be related with [what is identified as a moment.js bug in entitree's code](https://github.com/ogroppo/entitree/blob/017cb59/src/lib/formatDateClaim.js#L65)

**Comment by simon04** [comment]
JavaScript supports formatting dates using [`Date.toLocaleString`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString)

```js
var date = new Date(Date.UTC(2012, 11, 20, 3, 0, 0));
var options = { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' };
console.log(date.toLocaleDateString('de-DE', options));
// → "Donnerstag, 20. Dezember 2012"
```
